// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameClock = "c_clock"

// Clock mapped from table <c_clock>
type Clock struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // id
	UserID     string    `gorm:"column:user_id" json:"user_id"`                                            // 用户id
	SightID    string    `gorm:"column:sight_id" json:"sight_id"`                                          // 景点id
	SightName  string    `gorm:"column:sight_name" json:"sight_name"`                                      // 景点名称
	RegionID   string    `gorm:"column:region_id" json:"region_id"`                                        // 地点id
	RegionName string    `gorm:"column:region_name" json:"region_name"`                                    // 地点名称
	Images     string    `gorm:"column:images" json:"images"`                                              // 用户上传的图片
	Comment    string    `gorm:"column:comment" json:"comment"`                                            // 用户感受
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
}

// TableName Clock's table name
func (*Clock) TableName() string {
	return TableNameClock
}
