// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCollect = "c_collect"

// Collect mapped from table <c_collect>
type Collect struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // id
	UserID      string    `gorm:"column:user_id" json:"user_id"`                                            // 用户id
	SightID     string    `gorm:"column:sight_id" json:"sight_id"`                                          // 景点id
	SightImages string    `gorm:"column:sight_images" json:"sight_images"`                                  // 景点图片
	SightName   string    `gorm:"column:sight_name" json:"sight_name"`                                      // 景点名称
	StarLevel   string    `gorm:"column:star_level" json:"star_level"`                                      // 景点星级
	RegionID    string    `gorm:"column:region_id" json:"region_id"`                                        // 地点id
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
}

// TableName Collect's table name
func (*Collect) TableName() string {
	return TableNameCollect
}
