// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLabel = "c_label"

// Label mapped from table <c_label>
type Label struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Type     string `gorm:"column:type" json:"type"`         // 标签类型(用户，景点)
	Label    string `gorm:"column:label" json:"label"`       // 标签
	UniqueID string `gorm:"column:uniqueId" json:"uniqueId"` // 唯一标识（user_id,sight_id）
}

// TableName Label's table name
func (*Label) TableName() string {
	return TableNameLabel
}
