// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSight = "c_sight"

// Sight mapped from table <c_sight>
type Sight struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // id
	SightID     string    `gorm:"column:sight_id" json:"sight_id"`                                          // 景点id
	Name        string    `gorm:"column:name" json:"name"`                                                  // 景点名字
	Describe    string    `gorm:"column:describe" json:"describe"`                                          // 详细描述
	RegionID    string    `gorm:"column:region_id" json:"region_id"`                                        // 地点
	BestTime    string    `gorm:"column:best_time" json:"best_time"`                                        // 最佳旅游时间
	StarLevel   string    `gorm:"column:star_level" json:"star_level"`                                      // 星级
	HotLevel    string    `gorm:"column:hot_level" json:"hot_level"`                                        // 热门程度
	Unique      string    `gorm:"column:unique" json:"unique"`                                              // 特色
	CoverImages string    `gorm:"column:cover_images" json:"cover_images"`                                  // 封面图片
	SignImages  string    `gorm:"column:sign_images" json:"sign_images"`                                    // 地标图片
	ExtraImages string    `gorm:"column:extra_images" json:"extra_images"`                                  // 其他图片
	Extra       string    `gorm:"column:extra" json:"extra"`                                                // 其他
	Type        string    `gorm:"column:type" json:"type"`                                                  // 类型
	Label1      string    `gorm:"column:label1" json:"label1"`                                              // 标签1
	Label2      string    `gorm:"column:label2" json:"label2"`                                              // 标签2
	Label5      string    `gorm:"column:label5" json:"label5"`                                              // 标签5
	Label3      string    `gorm:"column:label3" json:"label3"`                                              // 标签3
	Label4      string    `gorm:"column:label4" json:"label4"`                                              // 标签4
	Address     string    `gorm:"column:address" json:"address"`                                            // 详细地址
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
	IsUser      string    `gorm:"column:is_user" json:"is_user"`                                            // 是否可用
}

// TableName Sight's table name
func (*Sight) TableName() string {
	return TableNameSight
}
