// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	hessian "github.com/apache/dubbo-go-hessian2"
	"time"
)

const TableNameUser = "sys_user"

// User mapped from table <sys_user>
type User struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 主键
	UserId         string    `gorm:"column:user_id" json:"userId"`                                             // 用户id
	Name           string    `gorm:"column:name" json:"name"`                                                  // 用户名
	Phone          string    `gorm:"column:phone" json:"phone"`                                                // 手机号
	Password       string    `gorm:"column:password" json:"password"`                                          // 密码
	Trend1         string    `gorm:"column:trend1" json:"trend1"`                                              // 用户趋向的景点类型
	Trend2         string    `gorm:"column:trend2" json:"trend2"`                                              // 用户趋向的景点类型
	Trend3         string    `gorm:"column:trend3" json:"trend3"`                                              // 用户趋向的景点类型
	IsProhibit     string    `gorm:"column:is_prohibit;not null" json:"is_prohibit"`                           // 账号是否封禁（0正常1封禁）
	ProhibitReason string    `gorm:"column:prohibit_reason" json:"prohibit_reason"`                            // 封禁理由
	RegionID       string    `gorm:"column:region_id" json:"region_id"`                                        // 用户所在省市
	Age            int32     `gorm:"column:age" json:"age"`                                                    // 年龄
	Sex            string    `gorm:"column:sex" json:"sex"`                                                    // 性别(0未知1男2女)
	Icon           string    `gorm:"column:icon" json:"icon"`                                                  // 头像
	Image          string    `gorm:"column:image" json:"image"`                                                // 背景图片（分号分割）
	Sign           string    `gorm:"column:sign" json:"sign"`                                                  // 个性签名
	Email          string    `gorm:"column:email" json:"email"`                                                // 电子邮箱
	IsMember       string    `gorm:"column:is_member;not null" json:"is_member"`                               // 是否为工作人员（0否1是）
	Extra          string    `gorm:"column:extra" json:"extra"`                                                // 其他
	CreateTime     time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime     time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}

func (u *User) JavaClassName() string {
	return "com.cai.funtour.po.User"
}

func init() {
	hessian.RegisterPOJO(&User{})
}
