server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        group: FUNTOUR_DEV
        namespace: 73545db9-50de-4b82-a402-431797133453
      server-addr: czytgc.com:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: public-consumer
          uri: lb://public-consumer
          predicates:
            - Path=/public/**
        - id: sight-consumer
          uri: lb://sight-consumer
          predicates:
            - Path=/sight/**
        - id: friend-consumer
          uri: lb://friend-consumer
          predicates:
            - Path=/friend/**
        - id: world-consumer
          uri: lb://world-consumer
          predicates:
            - Path=/world/**
logging:
  level:
    root: info
  config: classpath:log4j2.xml