# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ other/gateway ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7
      uses: docker/login-action@v1.14.1
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Images
      run: |
        docker build . -t candengbanzhan/gateway:RELEASE
        docker push candengbanzhan/gateway:RELEASE

    - name: Login Server
      uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_PASSWORD }}
    - name: Setup knownhosts
      run: ssh-keyscan zhiyuan.cai >> ~/.ssh/known_hosts
    - name: Run SSH Command
      run: |
        ssh root@zhiyuan.cai "docker pull candengbanzhan/gateway:RELEASE"
        ssh root@zhiyuan.cai "docker run -d -p 8771:8080 --name gateway candengbanzhan/gateway:RELEASE"

